documentation_media:
    url: "Documentation/"
    media_files:
        example_01:
            filename: "Example_01.PNG"
            name: 'img_example_01'
            width: 'content'
            caption: "Example of line drawing"
        example_02:
            filename: "Example_02.png"
            name: 'img_example_02'
            width: 'content'
            caption: "Left: good annotation of the leading flows of the ejection. Right: too many annotations of the flows."
        example_03:
            filename: "additional_example_05.png"
            name: 'img_example_03'
            width: 'content'
        example_04:
            filename: "additional_example_04.png"
            name: 'img_example_04'
            width: 'content'
        example_05:
            filename: "additional_example_03.png"
            name: 'img_example_05'
            width: 'content'
        img_td_01:
            filename: "time-distance-explained-01.png"
            name: 'img_td_01'
            width: 500
            caption: "First frame in the video for this jet."
        img_td_02:
            filename: "time-distance-explained-02.png"
            name: 'img_td_02'
            width: 500
            caption: "First column of the time-distance plot, obtained from the first frame of the video."
        img_td_03:
            filename: "time-distance-explained-03.png"
            name: 'img_td_03'
            width: 500
            caption: "Same operation, for a later frame."
        img_td_04:
            filename: "time-distance-explained-04.png"
            name: 'img_td_04'
            width: 500
            caption: "Individual columns, representing different time frames, together to form a time distance plot."
        img_td_05:
            filename: "time-distance-explained-05.png"
            name: 'img_td_05'
            width: 500
            caption: "Finalized time-distance plot."
sidebar_text: 
    control_text: |
        The display parameters can be adjusted here for a better visualization of the plot.

        By selecting 'Running difference', one displays the intensity difference between two time frames, rather than displaying the total intensity of each time frame.

        Log and linear scales refer to the distribution of intensity (but running difference arrays are displayed only in linear scale).

        Levels can be adjusted to saturate the image.
    no_ejection_info_text:
        text1: |
            You tried changing the levels, you tried switching to running difference, but you did not see any clear ejection in the time-distance plot.
        info1: |
            Please have a look on the right, under 'More info about this jet'. Play the movie in which the jet is developing, and the jet box is visible.
        text2: |
            Did you see the jet, or this is a case of mis-label with no jet present?

            Do you see the jet, but it is too faint to really show in the time-distance plot?

            Do you see the jet, but it is not at all aligned with the box, which can explain why we do not see any ejection in the time-distance plot?
        info2: |
            Please assess the situation before choosing an option below.
main_text:
    main_text_01: |
            Below is displayed a 'Time-Distance Plot' associated with a jet. 
            We want you to draw lines along the ejection visible in the plot (if any). Ejections can be made more visible using the "Image display controls" on the left side bar.
    about_this_task:
        intro_text: |
            Lines can be drawn directly on the data below: click right and maintain to draw. Release to end the line. 
            Several lines can be drawn, and lines can be deleted using the button below the image (left corner).
            
            When you are done, submit your classification in the left side bar.    

            If you do not see ejection and will not drawn any line, follow the guidance in the left side bar to assess why no ejection is visible and to submit your classification.
        example_text1: |
            We want you to draw line on the edge of the flows. 
            Different lines may be necessary to capture different features, and the curvature of the flow. It might also be easier to see the flows in running-difference (see left panel to switch).   
        example_text2: |
            We want to capture the leading edge of the ejection. You may need a few lines to capture its curvature. We do not want to draw each individual flow.
        example_text3: |
            Depending on the orientation of the box around the jet, the jet base could be at the bottom or at the top of the time-distance plot.
            Consequently, the flows could be evolving from bottom to top or from top to bottom, as shown on these two examples.

            Additionally, we sometimes see matter falling back, as in the second plot here. We do not report the flows that come back.
        example_text4: |
            Sometimes, the time range chose for the plot was very short. Generally, the flows are a bit streched as shown on this example.
        example_text5: |
            Sometimes, we do not see any flows. Adjusting the levels, switching on and off the running difference, changing to log scale... All of these tricks can help see flows.

            It is also possible that even with playing with the display, no flow can be seen in the time-distance plot. We kindly asked that you run the movie on the right to assess if possible the cause of the absence of flows.
            It could be that the jet is not moving that much, that the jet is very faint, or that there is no jet. 
            Sometimes, the jet is not aligned with the side of the box and that will also cause difficulty to see the flows in the time-distance plot.
            Finally, it is possible that the jet duration was not reported very accurately and that the movie is too short to capture the motion of the jet from its start.
    why_are_we_doing_this:
        text1: |
            The time-distance plots are one way to visualize the jet ejection over time. By drawing lines along the ejection, we get information to calculate the velocity of the ejection, which is an important paramter in understanding the physical process causing the jets.

            These plots have been computed automatically from the Solar Jet Hunter catalogue, using the box information derived from volunteers annotations. Some of these boxes might not be optimum for time-distance analysis, and some jets might be too faint to show in the time-distance plot.

            Additionally, some jets are very complex with multiple flows.

            for all of these reasons, we still need volunteers to look at these one by one, and to draw the lines on the time-distance plot: the complexity of the data makes automated analysis very difficult.

            Thank you for helping us out!
    why_ife:
        text1: |
            This webpage is an experimental feature of the Zooniverse ecosystem. 
            The Zooniverse team is exploring how individual projects, such as Solar Jet Hunter, could use personalized web apps to enable different ways of displaying or classifying data.
            More information on this effort has been described in a recent Zooniverse blog post (insert link here).

            On the Solar Jet Hunter side, we wanted to use two new functionalities: the possibility to adjust the levels of intensity in the time-distance plot,
            and the possibility to present the video of the jet with its box on the side.

            The slider with adjustable levels for the image is particularly useful to better visualize faint ejections in the time-distance plot.

            The movie with the jet and its box has two purposes: first, it is simply nice to see the jet at the origin of the time-distance plot, 
            and second, it is useful to understand the context around the time-distance plot. In particular, when the time-distance plot is unclear or unusual, 
            playing the video of the jet can be insightful and inform on the potentiel problems around this jet.
right_col_text:
    how_do_we_produce_td:
        text1: |
            To produce the time-distance plot, we use the jet box drawn in the video.

            We start on the first frame of the video.
        text2: |
            We consider only the data in the box, and squash it in the direction of the width of the box (We sum all pixels in one line). 
            By doing so we obtained one column representing the height of the box. This will be the first column in our time-distance plot.
        text3: |
            We repeat this operation for all the video frames, one by one.
        text4: |
            By placing all the columns besides each other, we are constructing the time-distance plot.
        text5: |
            By the end, we have a plot where the x-axis represent passing time, and the y-axis represent the height of the box. 
            Flows going up will be seen as going up in the plot, over time. We can sometimes also see flows going down in some jets.
