zooniverse_config:
    project_id: 11265
    workflow_id: 31505
    subject_set_id: 135159
project_urls:
    zooniverse_subjects: "https://www.zooniverse.org/api/subjects?subject_set_id={subject_set_id}&page={page}" 
    context_media: ""
